# SPDX-License-Identifier: GPL-2.0
obj-y += core/wmt_core.o core/wmt_ctrl.o core/wmt_func.o core/wmt_ic_soc.o \
	 core/wmt_lib.o core/wmt_conf.o core/btm_core.o core/psm_core.o \
	 core/stp_core.o
obj-y += linux/pri/stp_btif.o linux/pri/stp_dbg.o linux/pri/stp_exp.o \
	 linux/pri/wmt_dev.o linux/pri/wmt_exp.o
obj-y += linux/pub/osal.o linux/pub/bgw_desense.o
obj-$(CONFIG_MTK_CONSYS_BT_CHRDEV) += linux/pub/stp_chrdev_bt.o
